[build]
builder = "nixpacks"
buildCommand = "npm install && DATABASE_URL='postgresql://dummy:dummy@localhost/dummy' npx prisma generate"

[deploy]
startCommand = "npx prisma migrate deploy && node index.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
